// Shared server-side booking contract. This module is not a public asset.
const fields = ['senderName','senderEmail','origin','recipientName','recipientPhone','destination','contents','service'];
const shipmentStatuses = ['Shipment created','Picked up','In transit','At delivery facility','Out for delivery','Delivered','Delivery exception'];
// RFC 4122-style UUIDs are generated by the browser for each logical booking.
// Do not accept arbitrary strings here: the database column is UUID and a bad
// header must be rejected before a booking transaction can begin.
const validKey = value => typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
function normalizeBooking(body) {
  if (!body || fields.some(field => typeof body[field] !== 'string' || !body[field].trim())) return null;
  const weight = Number(body.weight);
  if (!['number','string'].includes(typeof body.weight) || !Number.isFinite(weight) || weight < 0.01 || weight > 99999999.99) return null;
  const payload = Object.fromEntries(fields.map(field => [field,body[field].trim()]));
  if (!['Economy','Priority','Express'].includes(payload.service)) return null;
  payload.weight = weight;
  return payload;
}
function normalizeAdminBooking(body) {
  const payload = normalizeBooking(body);
  if (!payload) return null;
  const ownerId = body.ownerId == null || body.ownerId === '' ? null : String(body.ownerId).trim();
  if (ownerId && !validKey(ownerId)) return null;
  const initialStatus = typeof body.initialStatus === 'string' ? body.initialStatus.trim() : '';
  if (!shipmentStatuses.includes(initialStatus)) return null;
  const initialProgress = Number(body.initialProgress);
  if (!Number.isInteger(initialProgress) || initialProgress < 0 || initialProgress > 100) return null;
  const expectedDelivery = body.expectedDelivery == null || body.expectedDelivery === '' ? null : String(body.expectedDelivery).trim();
  if (expectedDelivery && !/^\d{4}-\d{2}-\d{2}$/.test(expectedDelivery)) return null;
  return {ownerId, payload: {...payload, initialStatus, initialProgress, expectedDelivery}};
}
module.exports = {validKey,normalizeBooking,normalizeAdminBooking,shipmentStatuses};
