const http = require('node:http');
const { readFile } = require('node:fs/promises');
const { existsSync } = require('node:fs');
const path = require('node:path');
const { randomUUID, scryptSync, timingSafeEqual } = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

const root = __dirname, port = Number(process.env.PORT) || 3000, production = process.env.NODE_ENV === 'production';
const dataDirectory = process.env.DATA_DIR ? path.resolve(process.env.DATA_DIR) : path.join(root, 'data');
const db = new DatabaseSync(path.join(dataDirectory, 'swift-logistics.db'));
const supabaseUrl = process.env.SUPABASE_URL?.replace(/\/$/, '');
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;
const supabaseEnabled = Boolean(supabaseUrl && supabaseAnonKey);
const types = { '.css':'text/css; charset=utf-8', '.html':'text/html; charset=utf-8', '.js':'text/javascript; charset=utf-8', '.json':'application/json; charset=utf-8' };
db.exec(`PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'customer', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shipments (id TEXT PRIMARY KEY, owner_id TEXT REFERENCES users(id), sender_name TEXT NOT NULL, sender_email TEXT NOT NULL, origin TEXT NOT NULL, recipient_name TEXT NOT NULL, recipient_phone TEXT NOT NULL, destination TEXT NOT NULL, contents TEXT NOT NULL, weight REAL NOT NULL, service TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shipment_events (id INTEGER PRIMARY KEY AUTOINCREMENT, shipment_id TEXT NOT NULL REFERENCES shipments(id) ON DELETE CASCADE, title TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS support_tickets (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), name TEXT NOT NULL, email TEXT NOT NULL, topic TEXT NOT NULL, message TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);`);

const text = value => typeof value === 'string' && value.trim().length > 0;
const securityHeaders = { 'X-Content-Type-Options':'nosniff', 'X-Frame-Options':'DENY', 'Referrer-Policy':'strict-origin-when-cross-origin', 'Permissions-Policy':'camera=(), microphone=(), geolocation=()', 'Content-Security-Policy':"default-src 'self'; img-src 'self' https://images.unsplash.com; style-src 'self'; script-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'" };
const json = (res, status, body, extra = {}) => { res.writeHead(status, { ...securityHeaders, 'Content-Type':'application/json; charset=utf-8', 'Cache-Control':'no-store', ...extra }); res.end(JSON.stringify(body)); };
const clean = value => String(value ?? '').trim();
const tracking = () => `SWF-${randomUUID().replaceAll('-','').slice(0,8).toUpperCase()}`;
const supportId = () => `SUP-${randomUUID().replaceAll('-','').slice(0,8).toUpperCase()}`;
const hash = password => { const salt = randomUUID(); return `${salt}:${scryptSync(password, salt, 64).toString('hex')}`; };
const matches = (password, stored) => { const [salt, value] = stored.split(':'); const actual = scryptSync(password, salt, 64); return timingSafeEqual(actual, Buffer.from(value, 'hex')); };
async function body(req) { let data=''; for await (const part of req) { data += part; if (data.length > 100000) throw new Error('Request body too large'); } try { return JSON.parse(data); } catch { throw new Error('Send valid JSON.'); } }
function currentUser(req) { const token = (req.headers.cookie || '').split(';').map(v=>v.trim()).find(v=>v.startsWith('swift_session='))?.slice(14); if (!token) return null; const row = db.prepare(`SELECT users.id, users.name, users.email, users.role FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token=? AND sessions.expires_at>?`).get(token, new Date().toISOString()); return row || null; }
function shipment(row) { if (!row) return null; return { id:row.id, senderName:row.sender_name, senderEmail:row.sender_email, origin:row.origin, recipientName:row.recipient_name, recipientPhone:row.recipient_phone, destination:row.destination, contents:row.contents, weight:row.weight, service:row.service, status:row.status, createdAt:row.created_at, events:db.prepare('SELECT title, detail, created_at AS time FROM shipment_events WHERE shipment_id=? ORDER BY id DESC').all(row.id) }; }
function safeShipment(record) { const { senderEmail, recipientPhone, ...value } = record; return value; }
async function publicSupabaseTracking(id) {
  const response = await fetch(`${supabaseUrl}/rest/v1/rpc/track_shipment`, { method:'POST', headers:{ apikey:supabaseAnonKey, Authorization:`Bearer ${supabaseAnonKey}`, 'Content-Type':'application/json' }, body:JSON.stringify({ tracking_number:id }) });
  if (!response.ok) throw new Error('Supabase tracking lookup failed.');
  const [record] = await response.json();
  return record ? { id:record.id, origin:record.origin, destination:record.destination, service:record.service, status:record.status, createdAt:record.created_at, events:record.events || [] } : null;
}
const requests = new Map();
function allowed(req) { const key = req.socket.remoteAddress || 'unknown', now = Date.now(), windowMs = 15 * 60 * 1000; const active = (requests.get(key) || []).filter(time => time > now - windowMs); active.push(now); requests.set(key, active); return active.length <= 180; }

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`), user = currentUser(req);
  try {
    if (!allowed(req)) return json(res,429,{error:'Too many requests. Please try again later.'},{'Retry-After':'900'});
    if (req.method==='GET' && url.pathname==='/api/health') return json(res,200,{status:'ok',database:'sqlite'});
    if (req.method==='GET' && url.pathname==='/api/auth/me') return json(res,200,{user});
    if (req.method==='POST' && url.pathname==='/api/auth/register') { const b=await body(req); if (!text(b.name)||!/^\S+@\S+\.\S+$/.test(clean(b.email))||String(b.password||'').length<8) return json(res,422,{error:'Enter your name, a valid email, and a password of at least 8 characters.'}); const id=randomUUID(), token=randomUUID(), now=new Date().toISOString(); try { db.prepare('INSERT INTO users VALUES (?,?,?,?,?,?)').run(id,clean(b.name),clean(b.email).toLowerCase(),hash(b.password),'customer',now); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(token,id,new Date(Date.now()+604800000).toISOString()); return json(res,201,{user:{id,name:clean(b.name),email:clean(b.email).toLowerCase(),role:'customer'}},{'Set-Cookie':`swift_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`}); } catch { return json(res,409,{error:'An account with that email already exists.'}); } }
    if (req.method==='POST' && url.pathname==='/api/auth/login') { const b=await body(req), account=db.prepare('SELECT * FROM users WHERE email=?').get(clean(b.email).toLowerCase()); if (!account || !matches(String(b.password||''),account.password_hash)) return json(res,401,{error:'Email or password is incorrect.'}); const token=randomUUID(); db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(token,account.id,new Date(Date.now()+604800000).toISOString()); return json(res,200,{user:{id:account.id,name:account.name,email:account.email,role:account.role}},{'Set-Cookie':`swift_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`}); }
    if (req.method==='POST' && url.pathname==='/api/auth/logout') { const token=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('swift_session='))?.slice(14); if(token) db.prepare('DELETE FROM sessions WHERE token=?').run(token); return json(res,200,{ok:true},{'Set-Cookie':'swift_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'}); }
    if (req.method==='GET' && url.pathname==='/api/shipments') { if(!user) return json(res,401,{error:'Sign in to view your shipment history.'}); const rows=user.role==='staff'?db.prepare('SELECT * FROM shipments ORDER BY created_at DESC').all():db.prepare('SELECT * FROM shipments WHERE owner_id=? ORDER BY created_at DESC').all(user.id); return json(res,200,rows.map(row=>safeShipment(shipment(row)))); }
    if (req.method==='GET' && url.pathname.startsWith('/api/shipments/')) { const id=decodeURIComponent(url.pathname.split('/').pop()).toUpperCase(); const record=supabaseEnabled ? await publicSupabaseTracking(id) : safeShipment(shipment(db.prepare('SELECT * FROM shipments WHERE id=?').get(id))); return record?json(res,200,record):json(res,404,{error:'Shipment not found.'}); }
    if (req.method==='POST' && url.pathname==='/api/shipments') { const b=await body(req), required=['senderName','senderEmail','origin','recipientName','recipientPhone','destination','contents','weight','service']; if(required.some(k=>!text(String(b[k]??'')))||Number(b.weight)<=0) return json(res,422,{error:'Complete all shipment fields with a valid weight.'}); const id=tracking(), now=new Date().toISOString(); db.prepare('INSERT INTO shipments VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,user?.id||null,clean(b.senderName),clean(b.senderEmail),clean(b.origin),clean(b.recipientName),clean(b.recipientPhone),clean(b.destination),clean(b.contents),Number(b.weight),clean(b.service),'Shipment created',now); db.prepare('INSERT INTO shipment_events (shipment_id,title,detail,created_at) VALUES (?,?,?,?)').run(id,'Shipment created',`Collection scheduled in ${clean(b.origin)}`,now); return json(res,201,safeShipment(shipment(db.prepare('SELECT * FROM shipments WHERE id=?').get(id)))); }
    if (req.method==='PUT' && /^\/api\/shipments\/[^/]+\/status$/.test(url.pathname)) { if(user?.role!=='staff') return json(res,403,{error:'Staff access is required.'}); const b=await body(req), id=decodeURIComponent(url.pathname.split('/')[3]).toUpperCase(); if(!text(b.status)||!text(b.detail)) return json(res,422,{error:'Provide a status and update detail.'}); const update=db.prepare('UPDATE shipments SET status=? WHERE id=?').run(clean(b.status),id); if(!update.changes) return json(res,404,{error:'Shipment not found.'}); db.prepare('INSERT INTO shipment_events (shipment_id,title,detail,created_at) VALUES (?,?,?,?)').run(id,clean(b.status),clean(b.detail),new Date().toISOString()); return json(res,200,safeShipment(shipment(db.prepare('SELECT * FROM shipments WHERE id=?').get(id)))); }
    if (req.method==='POST' && url.pathname==='/api/support-tickets') { const b=await body(req); if(['name','email','topic','message'].some(k=>!text(b[k]))) return json(res,422,{error:'Complete your name, email, topic, and message.'}); const id=supportId(); db.prepare('INSERT INTO support_tickets VALUES (?,?,?,?,?,?,?,?)').run(id,user?.id||null,clean(b.name),clean(b.email),clean(b.topic),clean(b.message),'Open',new Date().toISOString()); return json(res,201,{id,status:'Open'}); }
    if (req.method==='GET' && url.pathname==='/api/support-tickets') { if(user?.role!=='staff') return json(res,403,{error:'Staff access is required.'}); return json(res,200,db.prepare('SELECT id, name, email, topic, message, status, created_at AS createdAt FROM support_tickets ORDER BY created_at DESC').all()); }
    if (req.method==='PUT' && /^\/api\/support-tickets\/[^/]+$/.test(url.pathname)) { if(user?.role!=='staff') return json(res,403,{error:'Staff access is required.'}); const b=await body(req), id=decodeURIComponent(url.pathname.split('/').pop()).toUpperCase(); if(!['Open','In progress','Resolved'].includes(b.status)) return json(res,422,{error:'Select a valid ticket status.'}); const update=db.prepare('UPDATE support_tickets SET status=? WHERE id=?').run(b.status,id); return update.changes?json(res,200,{id,status:b.status}):json(res,404,{error:'Support ticket not found.'}); }
    if (req.method!=='GET'&&req.method!=='HEAD') return json(res,404,{error:'Route not found.'}); const relative=path.normalize(url.pathname==='/'?'index.html':url.pathname.replace(/^\//,'')); const file=path.join(root,relative); if(!file.startsWith(root)||!existsSync(file)) return json(res,404,{error:'Not found.'}); const content=await readFile(file); res.writeHead(200,{...securityHeaders,...(production?{'Strict-Transport-Security':'max-age=31536000; includeSubDomains'}:{}),'Content-Type':types[path.extname(file)]||'application/octet-stream'}); res.end(req.method==='HEAD'?undefined:content);
  } catch(error) { console.error(error); json(res,error.message==='Request body too large'?413:400,{error:error.message||'Unable to process request.'}); }
});
server.listen(port,()=>console.log(`Swift Logistics is running at http://localhost:${port}`));
