const { randomUUID } = require('node:crypto');

const url = (process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL)?.replace(/\/$/, '');
const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;
const cookieName = 'swift_session';
const send = (res, status, body, headers = {}) => { res.statusCode = status; res.setHeader('Content-Type', 'application/json; charset=utf-8'); res.setHeader('Cache-Control', 'no-store'); Object.entries(headers).forEach(([name, value]) => res.setHeader(name, value)); res.end(JSON.stringify(body)); };
const read = req => new Promise((resolve, reject) => { let value=''; req.on('data', chunk => { value += chunk; if(value.length>100000) reject(new Error('Request body too large')); }); req.on('end', () => { try { resolve(value ? JSON.parse(value) : {}); } catch { reject(new Error('Send valid JSON.')); } }); });
const text = value => typeof value === 'string' && value.trim().length > 0;
const clean = value => String(value ?? '').trim();
const token = req => (req.headers.cookie || '').split(';').map(value => value.trim()).find(value => value.startsWith(`${cookieName}=`))?.slice(cookieName.length + 1);
async function request(path, options = {}, accessToken = key) { const response = await fetch(`${url}${path}`, { ...options, headers: { apikey:key, Authorization:`Bearer ${accessToken}`, 'Content-Type':'application/json', ...(options.headers || {}) } }); const body = await response.json().catch(() => null); if(!response.ok) throw new Error(body?.message || body?.error_description || 'Supabase request failed.'); return body; }
async function user(req) { const accessToken = token(req); if(!accessToken) return null; try { const account = await request('/auth/v1/user', {}, accessToken); const profiles = await request(`/rest/v1/profiles?id=eq.${account.id}&select=id,name,role`, {}, accessToken); return { ...account, profile:profiles[0], token:accessToken }; } catch { return null; } }
const safe = shipment => { const { sender_email, recipient_phone, shipment_events, ...rest } = shipment; return { id:rest.id, senderName:rest.sender_name, origin:rest.origin, recipientName:rest.recipient_name, destination:rest.destination, contents:rest.contents, weight:rest.weight, service:rest.service, status:rest.status, currentCountry:rest.current_country, currentState:rest.current_state, currentCity:rest.current_city, progress:rest.progress || 0, expectedDelivery:rest.expected_delivery, createdAt:rest.created_at, events:(shipment_events || []).map(event => ({ title:event.title, detail:event.detail, time:event.created_at })) }; };

module.exports = async (req, res) => {
  if (!url || !key) return send(res, 500, { error:'Supabase environment variables are not configured.' });
  const path = new URL(req.url, 'http://localhost').pathname;
  try {
    if (req.method === 'GET' && path === '/api/health') return send(res, 200, { status:'ok', database:'supabase' });
    if (req.method === 'GET' && path === '/api/auth/me') { const account = await user(req); return send(res, 200, { user:account?.profile ? { id:account.id, name:account.profile.name, email:account.email, role:account.profile.role } : null }); }
    if (req.method === 'POST' && path === '/api/auth/register') { const body=await read(req); if(!text(body.name)||!/^\S+@\S+\.\S+$/.test(clean(body.email))||String(body.password || '').length<8) return send(res,422,{error:'Enter your name, a valid email, and a password of at least 8 characters.'}); const account=await request('/auth/v1/signup',{method:'POST',body:JSON.stringify({email:clean(body.email),password:body.password,data:{name:clean(body.name)}})}); if(!account.access_token) return send(res,202,{message:'Check your email to confirm your account before signing in.'}); return send(res,201,{user:{id:account.user.id,name:clean(body.name),email:account.user.email,role:'customer'}},{'Set-Cookie':`${cookieName}=${account.access_token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=3600`}); }
    if (req.method === 'POST' && path === '/api/auth/login') { const body=await read(req); const account=await request('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:clean(body.email),password:body.password})}); const profiles=await request(`/rest/v1/profiles?id=eq.${account.user.id}&select=name,role`,{},account.access_token); return send(res,200,{user:{id:account.user.id,name:profiles[0]?.name,email:account.user.email,role:profiles[0]?.role || 'customer'}},{'Set-Cookie':`${cookieName}=${account.access_token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${account.expires_in}`}); }
    if (req.method === 'POST' && path === '/api/auth/forgot-password') { const body=await read(req); if(!/^\S+@\S+\.\S+$/.test(clean(body.email))) return send(res,422,{error:'Enter a valid email address.'}); await request('/auth/v1/recover',{method:'POST',body:JSON.stringify({email:clean(body.email),redirect_to:`${req.headers['x-forwarded-proto'] || 'https'}://${req.headers.host}/reset-password`})}); return send(res,200,{message:'If that email has an account, a reset link has been sent.'}); }
    if (req.method === 'POST' && path === '/api/auth/reset-password') { const body=await read(req); if(String(body.password || '').length<8 || !text(body.accessToken)) return send(res,422,{error:'Use a valid recovery link and a password of at least 8 characters.'}); await request('/auth/v1/user',{method:'PUT',body:JSON.stringify({password:body.password})},clean(body.accessToken)); return send(res,200,{message:'Your password has been updated. You can now sign in.'}); }
    if (req.method === 'POST' && path === '/api/auth/logout') return send(res,200,{ok:true},{'Set-Cookie':`${cookieName}=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0`});
    if (req.method === 'GET' && path === '/api/shipments') { const account=await user(req); if(!account?.profile) return send(res,401,{error:'Sign in to view your shipment history.'}); const records=await request('/rest/v1/shipments?select=*,shipment_events(*)&order=created_at.desc',{},account.token); return send(res,200,records.map(safe)); }
    if (req.method === 'GET' && path.startsWith('/api/shipments/')) { const id=decodeURIComponent(path.split('/').pop()).toUpperCase(); const records=await request('/rest/v1/rpc/track_shipment',{method:'POST',body:JSON.stringify({tracking_number:id})}); if(!records[0]) return send(res,404,{error:'Shipment not found.'}); const record=records[0]; return send(res,200,{id:record.id,origin:record.origin,destination:record.destination,service:record.service,status:record.status,currentCountry:record.current_country,currentState:record.current_state,currentCity:record.current_city,progress:record.progress,expectedDelivery:record.expected_delivery,createdAt:record.created_at,events:record.events || []}); }
    if (req.method === 'POST' && path === '/api/shipments') { const account=await user(req), body=await read(req), fields=['senderName','senderEmail','origin','recipientName','recipientPhone','destination','contents','weight','service']; if(fields.some(field=>!text(String(body[field]??'')))||Number(body.weight)<=0) return send(res,422,{error:'Complete all shipment fields with a valid weight.'}); const id=`SWF-${randomUUID().replaceAll('-','').slice(0,8).toUpperCase()}`; const row={id,owner_id:account?.id || null,sender_name:clean(body.senderName),sender_email:clean(body.senderEmail),origin:clean(body.origin),recipient_name:clean(body.recipientName),recipient_phone:clean(body.recipientPhone),destination:clean(body.destination),contents:clean(body.contents),weight:Number(body.weight),service:clean(body.service),status:'Shipment created'}; await request('/rest/v1/shipments',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)},account?.token || key); await request('/rest/v1/shipment_events',{method:'POST',body:JSON.stringify({shipment_id:id,title:'Shipment created',detail:`Collection scheduled in ${row.origin}`})},account?.token || key); return send(res,201,{...safe({...row,shipment_events:[]}),events:[{title:'Shipment created',detail:`Collection scheduled in ${row.origin}`,time:new Date().toISOString()}]}); }
    if (req.method === 'PUT' && /^\/api\/shipments\/[^/]+\/status$/.test(path)) { const account=await user(req), body=await read(req), id=decodeURIComponent(path.split('/')[3]).toUpperCase(), progress=Number(body.progress); if(account?.profile?.role!=='staff') return send(res,403,{error:'Staff access is required.'}); if(!text(body.status)||!text(body.detail)||!Number.isInteger(progress)||progress<0||progress>100) return send(res,422,{error:'Provide a status, detail, and progress from 0 to 100.'}); const location=[clean(body.city),clean(body.state),clean(body.country)].filter(Boolean).join(', '); await request(`/rest/v1/shipments?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:clean(body.status),current_country:clean(body.country)||null,current_state:clean(body.state)||null,current_city:clean(body.city)||null,progress,expected_delivery:clean(body.expectedDelivery)||null})},account.token); await request('/rest/v1/shipment_events',{method:'POST',body:JSON.stringify({shipment_id:id,title:clean(body.status),detail:`${clean(body.detail)}${location?` — ${location}`:''}`})},account.token); return send(res,200,{id,status:clean(body.status)}); }
    if (req.method === 'POST' && path === '/api/support-tickets') { const account=await user(req), body=await read(req); if(['name','email','topic','message'].some(field=>!text(body[field]))) return send(res,422,{error:'Complete your name, email, topic, and message.'}); const id=`SUP-${randomUUID().replaceAll('-','').slice(0,8).toUpperCase()}`; await request('/rest/v1/support_tickets',{method:'POST',body:JSON.stringify({id,user_id:account?.id || null,name:clean(body.name),email:clean(body.email),topic:clean(body.topic),message:clean(body.message)})},account?.token || key); return send(res,201,{id,status:'Open'}); }
    if (req.method === 'GET' && path === '/api/support-tickets') { const account=await user(req); if(account?.profile?.role!=='staff') return send(res,403,{error:'Staff access is required.'}); return send(res,200,await request('/rest/v1/support_tickets?select=*&order=created_at.desc',{},account.token)); }
    if (req.method === 'PUT' && /^\/api\/support-tickets\/[^/]+$/.test(path)) { const account=await user(req), body=await read(req), id=decodeURIComponent(path.split('/').pop()).toUpperCase(); if(account?.profile?.role!=='staff') return send(res,403,{error:'Staff access is required.'}); if(!['Open','In progress','Resolved'].includes(body.status)) return send(res,422,{error:'Select a valid ticket status.'}); await request(`/rest/v1/support_tickets?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status:body.status})},account.token); return send(res,200,{id,status:body.status}); }
    return send(res,404,{error:'Route not found.'});
  } catch(error) { return send(res,400,{error:error.message || 'Request failed.'}); }
};
